/**
 * Amplify configuration — the AWS equivalent of the old firebase/config.js.
 *
 * `amplify_outputs.json` is generated by the backend deploy (`ampx sandbox` in
 * dev, Amplify Hosting in prod) and holds the GraphQL endpoint, region and
 * Cognito user-pool details. It contains only public client config (like the
 * old firebaseConfig did) — access is gated by Cognito + the data auth rules.
 *
 * This module MUST be imported once, before anything that uses the data client
 * or Auth (see main.jsx). It has no exports beyond the side-effect of
 * configuring Amplify.
 */
import { Amplify } from 'aws-amplify';
import outputs from '../amplify_outputs.json';

Amplify.configure(outputs);
